### PR TITLE
Refactor and add authenticating file proxy

### PR DESCRIPTION
**Pull request by ThinkChaos**
I refactored the code a lot and added the file proxy mentioned in #45 to be able to download files.

One aspect of the refactor was to use a `log.Logger` instead of fmt so that we can switch to Caddy 2's log system easily.
I also cleaned the FS cache implementation to use custom less types.

If you're not interested in the refactor, I can open a different PR with just the file proxy feature.

### CODE REVIEW

**Comment by techknowlogick** [comment]
🙏 Thank you so much for this PR 😄 The refactor of my original code was very much needed and I appreciate you taking on that task.

I'll hopefully have time to review this today and get it merged.

**Review by techknowlogick — APPROVED** [review]

**Comment by CMCDragonkai** [comment]
Is this feature on by default now? As in all requests are properly proxied as per #45? There's no config change required?

**Comment by techknowlogick** [comment]
@CMCDragonkai that's correct. I use this on https://dl.gitea.io and no config changes were required.

**Comment by CMCDragonkai** [comment]
Awesome. Wondering why you use it for dl.gitea.io? Is it for caching purposes?

On 8 April 2020 12:11:24 GMT+10:00, techknowlogick <notifications@github.com> wrote:
>@CMCDragonkai that's correct. I use this on https://dl.gitea.io and no
>config changes were required.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/techknowlogick/caddy-s3browser/pull/60#issuecomment-610712162

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
